apiVersion: v1
kind: Secret
metadata:
  name: pdfprocessor-secrets
  namespace: pdfprocessor
type: Opaque
stringData:
  # MongoDB Atlas URI (substitua pelo valor real em produção)
  mongodb-uri: "mongodb+srv://user:password@cluster.mongodb.net/pdfprocessor?retryWrites=true&w=majority"
  
  # JWT Secret (mínimo 256 bits para HS256)
  jwt-secret: "your-super-secret-key-minimum-256-bits-for-hs256-change-in-production"
