apiVersion: v1
kind: Service
metadata:
  name: pdfprocessor-api
  namespace: pdfprocessor
  labels:
    app: pdfprocessor-api
spec:
  type: ClusterIP  # Apenas acesso interno (Ingress faz o externo)
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: pdfprocessor-api
